defmodule :"Elixir.Angle.Repo.Migrations.Update-category-resource" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:categories) do
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :form_schema, :map, default: %{}
      modify :attribute_schema, :map, default: %{}
    end

    create table(:bids, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :decimal, null: false
      add :bid_type, :text, null: false

      add :bid_time, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:items,
            column: :id,
            name: "bids_item_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "bids_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:bids, "bids_item_id_fkey")

    drop constraint(:bids, "bids_user_id_fkey")

    drop table(:bids)

    alter table(:categories) do
      modify :attribute_schema, :map, default: nil
      modify :form_schema, :map, default: nil
      modify :created_at, :utc_datetime_usec, default: nil
    end
  end
end
