defmodule :"Elixir.Angle.Repo.Migrations.Update option value attributes" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:option_set_values) do
      add :parent_set_id, :uuid
      add :parent_value, :text
    end
  end

  def down do
    alter table(:option_set_values) do
      remove :parent_value
      remove :parent_set_id
    end
  end
end
