defmodule Angle.Repo.Migrations.AddParentIdToOptionSets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:option_sets) do
      add :parent_id,
          references(:option_sets,
            column: :id,
            name: "option_sets_parent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:option_sets, "option_sets_parent_id_fkey")

    alter table(:option_sets) do
      remove :parent_id
    end
  end
end
