defmodule Angle.Repo.Migrations.RegenMigrations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users, primary_key: false) do
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :confirmed_at, :utc_datetime_usec
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:user_roles, primary_key: false) do
      add :role_id, :uuid, null: false
      add :expires_at, :utc_datetime_usec
      add :scope_type, :text
      add :scope_id, :bigint

      add :granted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_roles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :granted_by_id,
          references(:users,
            column: :id,
            name: "user_roles_granted_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :scope, :text, null: false
      add :active, :boolean

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:roles, [:name, :scope], name: "roles_name_scope_key")

    create table(:items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :starting_price, :decimal
      add :reserve_price, :decimal
      add :current_price, :decimal
      add :auction_type_id, :uuid
      add :bid_increment, :decimal
      add :slug, :text
      add :start_time, :utc_datetime_usec
      add :end_time, :utc_datetime_usec
      add :category_id, :uuid
      add :lot_number, :text
      add :publication_status, :text
      add :auction_status, :text
      add :condition, :text
      add :location, :text
      add :attributes, :map, null: false
      add :sale_type, :text, null: false
      add :auction_format, :text
      add :buy_now_price, :decimal
      add :view_count, :bigint, default: 0
      add :watcher_count, :bigint, default: 0
      add :bid_count, :bigint, default: 0
      add :question_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_by_id,
          references(:users,
            column: :id,
            name: "items_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:items, [:auction_status, :publication_status],
             name: "items_published_auction_idx",
             where:
               "(((publication_status)::text = 'published'::text) AND ((auction_status)::text = ANY ((ARRAY['scheduled'::character varying, 'active'::character varying, 'ended'::character varying])::text[])))"
           )

    create unique_index(:items, [:slug, :title], name: "items_slug_title_index")

    create table(:item_activities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :activity_type, :text, null: false
      add :description, :text
      add :metadata, :map
      add :ip_address, :text
      add :user_agent, :text
      add :session_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:items,
            column: :id,
            name: "item_activities_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "item_activities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :created_at, :utc_datetime_usec, null: false

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :slug, :text
      add :attribute_schema, :map, null: false
      add :form_schema, :map, null: false
      add :image_url, :text

      add :parent_id,
          references(:categories,
            column: :id,
            name: "categories_parent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:categories, [:name, :parent_id], name: "categories_name_parent_index")

    create unique_index(:categories, [:slug], name: "categories_slug_index")

    create table(:auction_bids, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :decimal, null: false
      add :bid_type, :text, null: false

      add :bid_time, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:items,
            column: :id,
            name: "auction_bids_item_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "auction_bids_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create constraint(:items, :valid_auction_status,
             check: """
               (((auction_status IS NULL) OR ((auction_status)::text = ANY (ARRAY[('scheduled'::character varying)::text, ('active'::character varying)::text, ('paused'::character varying)::text, ('ended'::character varying)::text, ('sold'::character varying)::text, ('cancelled'::character varying)::text]))))
             """
           )
  end

  def down do
    drop_if_exists constraint(:items, :valid_auction_status)

    drop constraint(:auction_bids, "auction_bids_item_id_fkey")

    drop constraint(:auction_bids, "auction_bids_user_id_fkey")

    drop table(:auction_bids)

    drop_if_exists unique_index(:categories, [:slug], name: "categories_slug_index")

    drop_if_exists unique_index(:categories, [:name, :parent_id],
                     name: "categories_name_parent_index"
                   )

    drop constraint(:categories, "categories_parent_id_fkey")

    drop table(:categories)

    drop constraint(:item_activities, "item_activities_item_id_fkey")

    drop constraint(:item_activities, "item_activities_user_id_fkey")

    drop table(:item_activities)

    drop_if_exists unique_index(:items, [:slug, :title], name: "items_slug_title_index")

    drop constraint(:items, "items_created_by_id_fkey")

    drop_if_exists index(:items, [:auction_status, :publication_status],
                     name: "items_published_auction_idx"
                   )

    drop table(:items)

    drop_if_exists unique_index(:roles, [:name, :scope], name: "roles_name_scope_key")

    drop table(:roles)

    drop constraint(:user_roles, "user_roles_user_id_fkey")

    drop constraint(:user_roles, "user_roles_granted_by_id_fkey")

    drop table(:user_roles)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
