defmodule :"Elixir.Angle.Repo.Migrations.Update item fields" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      remove :question_count
      remove :bid_count
      remove :watcher_count
      remove :auction_type_id
      modify :auction_format, :text, default: "standard"
      modify :sale_type, :text, default: "auction"
      modify :condition, :text, default: "new"
      modify :auction_status, :text, default: "pending"
      modify :publication_status, :text, default: "draft"
      modify :starting_price, :decimal, null: false

      modify :category_id,
             references(:categories,
               column: :id,
               name: "items_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:items, [:category_id])

    alter table(:bids) do
      modify :user_id, :uuid, null: false
      modify :item_id, :uuid, null: false
    end
  end

  def down do
    alter table(:bids) do
      modify :item_id, :uuid, null: true
      modify :user_id, :uuid, null: true
    end

    drop_if_exists index(:items, [:category_id])

    drop constraint(:items, "items_category_id_fkey")

    alter table(:items) do
      modify :category_id, :uuid
      modify :starting_price, :decimal, null: true
      modify :publication_status, :text, default: nil
      modify :auction_status, :text, default: nil
      modify :condition, :text, default: nil
      modify :sale_type, :text, default: nil
      modify :auction_format, :text, default: nil
      add :auction_type_id, :uuid
      add :watcher_count, :bigint, default: 0
      add :bid_count, :bigint, default: 0
      add :question_count, :bigint, default: 0
    end
  end
end
