defmodule Angle.Repo.Migrations.AddOptionSets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:option_sets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:option_sets, [:slug], name: "option_sets_slug_index")

    create table(:option_set_values, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :value, :text, null: false
      add :label, :text, null: false
      add :metadata, :map, default: %{}
      add :sort_order, :bigint, default: 0
      add :is_active, :boolean, default: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :option_set_id,
          references(:option_sets,
            column: :id,
            name: "option_set_values_option_set_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:option_set_values, "option_set_values_option_set_id_fkey")

    drop table(:option_set_values)

    drop_if_exists unique_index(:option_sets, [:slug], name: "option_sets_slug_index")

    drop table(:option_sets)
  end
end
