defmodule Angle.Repo.Migrations.AddPermissionSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:role_permissions, primary_key: false) do
      add :role_id,
          references(:roles,
            column: :id,
            name: "role_permissions_role_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :permission_id, :uuid, null: false

      add :granted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :granted_by_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:permissions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:role_permissions) do
      modify :permission_id,
             references(:permissions,
               column: :id,
               name: "role_permissions_permission_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :granted_by_id,
             references(:users,
               column: :id,
               name: "role_permissions_granted_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:permissions) do
      add :name, :text, null: false
      add :resource, :text, null: false
      add :action, :text, null: false
      add :scope, :text, null: false, default: "system"
      add :description, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:permissions, [:name, :resource, :action],
             name: "permissions_name_resource_action_index"
           )
  end

  def down do
    drop_if_exists unique_index(:permissions, [:name, :resource, :action],
                     name: "permissions_name_resource_action_index"
                   )

    alter table(:permissions) do
      remove :updated_at
      remove :created_at
      remove :description
      remove :scope
      remove :action
      remove :resource
      remove :name
    end

    drop constraint(:role_permissions, "role_permissions_permission_id_fkey")

    drop constraint(:role_permissions, "role_permissions_granted_by_id_fkey")

    alter table(:role_permissions) do
      modify :granted_by_id, :uuid
      modify :permission_id, :uuid
    end

    drop table(:permissions)

    drop constraint(:role_permissions, "role_permissions_role_id_fkey")

    drop table(:role_permissions)
  end
end
