defmodule Angle.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:store_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :store_name, :text, null: false
      add :contact_phone, :text
      add :whatsapp_link, :text
      add :location, :text
      add :address, :text
      add :delivery_preference, :text, default: "you_arrange"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "store_profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:store_profiles, [:user_id], name: "store_profiles_unique_user_index")
  end

  def down do
    drop_if_exists unique_index(:store_profiles, [:user_id],
                     name: "store_profiles_unique_user_index"
                   )

    drop constraint(:store_profiles, "store_profiles_user_id_fkey")

    drop table(:store_profiles)
  end
end
