defmodule Angle.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Migrate existing store_name data to store_profiles
    execute("""
    INSERT INTO store_profiles (id, user_id, store_name, delivery_preference, inserted_at, updated_at)
    SELECT gen_random_uuid(), id, store_name, 'you_arrange', NOW(), NOW()
    FROM users
    WHERE store_name IS NOT NULL
    ON CONFLICT (user_id) DO NOTHING
    """)

    alter table(:users) do
      remove :store_name
    end
  end

  def down do
    alter table(:users) do
      add :store_name, :text
    end
  end
end
