defmodule Angle.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:item_similarities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :similarity_score, :float, null: false
      add :reason, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_item_id,
          references(:items,
            column: :id,
            name: "item_similarities_source_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :similar_item_id,
          references(:items,
            column: :id,
            name: "item_similarities_similar_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:item_similarities, [:source_item_id, :similarity_score])

    create unique_index(:item_similarities, [:source_item_id, :similar_item_id],
             name: "item_similarities_unique_source_similar_index"
           )
  end

  def down do
    drop_if_exists unique_index(:item_similarities, [:source_item_id, :similar_item_id],
                     name: "item_similarities_unique_source_similar_index"
                   )

    drop constraint(:item_similarities, "item_similarities_source_item_id_fkey")

    drop constraint(:item_similarities, "item_similarities_similar_item_id_fkey")

    drop_if_exists index(:item_similarities, [:source_item_id, :similarity_score])

    drop table(:item_similarities)
  end
end
