defmodule Angle.Repo.Migrations.AddCodeInterfacesForRecommendations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_interests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :interest_score, :float, null: false, default: 0.0

      add :last_interaction_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :interaction_count, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_interests_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :category_id,
          references(:categories,
            column: :id,
            name: "user_interests_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:user_interests, [:user_id, :interest_score])

    create unique_index(:user_interests, [:user_id, :category_id],
             name: "user_interests_unique_user_category_index"
           )

    create table(:reviews, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :rating, :bigint, null: false
      add :comment, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:orders,
            column: :id,
            name: "reviews_order_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :reviewer_id,
          references(:users,
            column: :id,
            name: "reviews_reviewer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :seller_id,
          references(:users,
            column: :id,
            name: "reviews_seller_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:reviews, [:seller_id])

    create unique_index(:reviews, [:order_id], name: "reviews_unique_order_review_index")

    create table(:recommended_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :recommendation_score, :float, null: false
      add :recommendation_reason, :text
      add :rank, :bigint, null: false

      add :generated_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "recommended_items_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :item_id,
          references(:items,
            column: :id,
            name: "recommended_items_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:recommended_items, [:generated_at])

    create index(:recommended_items, [:user_id, :rank])

    create unique_index(:recommended_items, [:user_id, :item_id],
             name: "recommended_items_unique_user_item_index"
           )

    alter table(:items) do
      modify :attributes, :map
    end

    create table(:item_similarities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :similarity_score, :float, null: false
      add :reason, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_item_id,
          references(:items,
            column: :id,
            name: "item_similarities_source_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :similar_item_id,
          references(:items,
            column: :id,
            name: "item_similarities_similar_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:item_similarities, [:source_item_id, :similarity_score])

    create unique_index(:item_similarities, [:source_item_id, :similar_item_id],
             name: "item_similarities_unique_source_similar_index"
           )

    create table(:images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :owner_type, :text, null: false
      add :owner_id, :uuid, null: false
      add :storage_key, :text, null: false
      add :variants, :map, null: false, default: %{}
      add :position, :bigint, null: false, default: 0
      add :file_size, :bigint, null: false
      add :mime_type, :text, null: false
      add :width, :bigint, null: false
      add :height, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:images, [:owner_type, :owner_id, :position],
             name: "images_unique_position_index"
           )

    execute "ALTER TABLE categories ALTER COLUMN attribute_schema DROP DEFAULT"

    execute "ALTER TABLE categories ALTER COLUMN attribute_schema TYPE jsonb[] USING '{}'::jsonb[]"

    execute "ALTER TABLE categories ALTER COLUMN attribute_schema SET DEFAULT '{}'"
  end

  def down do
    execute "ALTER TABLE categories ALTER COLUMN attribute_schema DROP DEFAULT"

    execute "ALTER TABLE categories ALTER COLUMN attribute_schema TYPE jsonb USING to_jsonb(attribute_schema)"

    execute "ALTER TABLE categories ALTER COLUMN attribute_schema SET DEFAULT '[]'::jsonb"

    drop_if_exists unique_index(:images, [:owner_type, :owner_id, :position],
                     name: "images_unique_position_index"
                   )

    drop table(:images)

    drop_if_exists unique_index(:item_similarities, [:source_item_id, :similar_item_id],
                     name: "item_similarities_unique_source_similar_index"
                   )

    drop constraint(:item_similarities, "item_similarities_source_item_id_fkey")

    drop constraint(:item_similarities, "item_similarities_similar_item_id_fkey")

    drop_if_exists index(:item_similarities, [:source_item_id, :similarity_score])

    drop table(:item_similarities)

    alter table(:items) do
      modify :attributes, :map
    end

    drop_if_exists unique_index(:recommended_items, [:user_id, :item_id],
                     name: "recommended_items_unique_user_item_index"
                   )

    drop constraint(:recommended_items, "recommended_items_user_id_fkey")

    drop constraint(:recommended_items, "recommended_items_item_id_fkey")

    drop_if_exists index(:recommended_items, [:user_id, :rank])

    drop_if_exists index(:recommended_items, [:generated_at])

    drop table(:recommended_items)

    drop_if_exists unique_index(:reviews, [:order_id], name: "reviews_unique_order_review_index")

    drop constraint(:reviews, "reviews_order_id_fkey")

    drop constraint(:reviews, "reviews_reviewer_id_fkey")

    drop constraint(:reviews, "reviews_seller_id_fkey")

    drop_if_exists index(:reviews, [:seller_id])

    drop table(:reviews)

    drop_if_exists unique_index(:user_interests, [:user_id, :category_id],
                     name: "user_interests_unique_user_category_index"
                   )

    drop constraint(:user_interests, "user_interests_user_id_fkey")

    drop constraint(:user_interests, "user_interests_category_id_fkey")

    drop_if_exists index(:user_interests, [:user_id, :interest_score])

    drop table(:user_interests)
  end
end
