defmodule Angle.Repo.Migrations.AddSearchVectorToItems do
  @moduledoc """
  Adds full-text search infrastructure to the items table.

  Manual migration (not generated by ash_postgres). Adds pg_trgm extension,
  search_vector tsvector column with auto-populate trigger, and GIN indexes
  for full-text and trigram search.
  """
  use Ecto.Migration

  def up do
    # Enable pg_trgm extension for fuzzy matching
    execute "CREATE EXTENSION IF NOT EXISTS pg_trgm"

    # Add tsvector column
    alter table(:items) do
      add :search_vector, :tsvector
    end

    # Backfill existing rows (before trigger is attached to avoid redundant recomputation)
    execute """
    UPDATE items SET search_vector =
      setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
      setweight(to_tsvector('english', coalesce(description, '')), 'B')
    """

    # Create trigger function to keep search_vector in sync
    execute """
    CREATE OR REPLACE FUNCTION items_search_vector_trigger() RETURNS trigger AS $$
    BEGIN
      NEW.search_vector :=
        setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.description, '')), 'B');
      RETURN NEW;
    END
    $$ LANGUAGE plpgsql
    """

    # Attach trigger to items table
    execute """
    CREATE TRIGGER items_search_vector_update
      BEFORE INSERT OR UPDATE OF title, description ON items
      FOR EACH ROW EXECUTE FUNCTION items_search_vector_trigger()
    """

    # GIN index on tsvector for fast full-text search
    create index(:items, [:search_vector], using: :gin, name: "items_search_vector_idx")

    # GIN trigram index on title for fuzzy matching (raw SQL needed for gin_trgm_ops operator class)
    execute "CREATE INDEX items_title_trgm_idx ON items USING gin (title gin_trgm_ops)"
  end

  def down do
    execute "DROP TRIGGER IF EXISTS items_search_vector_update ON items"
    execute "DROP FUNCTION IF EXISTS items_search_vector_trigger()"
    drop_if_exists index(:items, [:search_vector], name: "items_search_vector_idx")
    execute "DROP INDEX IF EXISTS items_title_trgm_idx"

    alter table(:items) do
      remove :search_vector
    end

    execute "DROP EXTENSION IF EXISTS pg_trgm"
  end
end
