defmodule Angle.Repo.Migrations.AddWatchlistItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:watchlist_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "watchlist_items_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :item_id,
          references(:items,
            column: :id,
            name: "watchlist_items_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:watchlist_items, [:user_id, :item_id],
             name: "watchlist_items_unique_user_item_index"
           )
  end

  def down do
    drop_if_exists unique_index(:watchlist_items, [:user_id, :item_id],
                     name: "watchlist_items_unique_user_item_index"
                   )

    drop constraint(:watchlist_items, "watchlist_items_user_id_fkey")

    drop constraint(:watchlist_items, "watchlist_items_item_id_fkey")

    drop table(:watchlist_items)
  end
end
