defmodule Angle.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_verifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "user_verifications_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :phone_verified, :boolean, null: false, default: false
      add :phone_verified_at, :utc_datetime_usec
      add :id_verified, :boolean, null: false, default: false
      add :id_document_url, :text
      add :id_verified_at, :utc_datetime_usec
      add :id_verification_status, :text, null: false, default: "not_submitted"
      add :id_rejection_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:user_verifications, [:user_id],
             name: "user_verifications_unique_user_verification_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_verifications, [:user_id],
                     name: "user_verifications_unique_user_verification_index"
                   )

    drop constraint(:user_verifications, "user_verifications_user_id_fkey")

    drop table(:user_verifications)
  end
end
