defmodule Angle.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      modify :attributes, :map
    end
  end

  def down do
    alter table(:items) do
      modify :attributes, :map
    end
  end
end
