defmodule Angle.Repo.Migrations.CreateOtpsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:otps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "otps_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :confirmation_token, :text, null: false
      add :purpose, :text, null: false, default: "confirm_new_user"
      add :expires_at, :utc_datetime_usec, null: false
      add :used_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:otps, "otps_user_id_fkey")

    drop table(:otps)
  end
end
