defmodule Angle.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:wallet_transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :wallet_id, :uuid, null: false
      add :amount, :decimal, null: false, precision: 15, scale: 2
      add :transaction_type, :text, null: false
      add :balance_before, :decimal, null: false, precision: 15, scale: 2
      add :balance_after, :decimal, null: false, precision: 15, scale: 2
      add :reference, :text, null: false
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:user_wallets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:wallet_transactions) do
      modify :wallet_id,
             references(:user_wallets,
               column: :id,
               name: "wallet_transactions_wallet_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:user_wallets) do
      add :user_id,
          references(:users,
            column: :id,
            name: "user_wallets_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :balance, :decimal, null: false, default: "0", precision: 15, scale: 2
      add :total_deposited, :decimal, null: false, default: "0", precision: 15, scale: 2
      add :total_withdrawn, :decimal, null: false, default: "0", precision: 15, scale: 2

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:user_wallets, [:user_id], name: "user_wallets_unique_user_wallet_index")
  end

  def down do
    drop_if_exists unique_index(:user_wallets, [:user_id],
                     name: "user_wallets_unique_user_wallet_index"
                   )

    drop constraint(:user_wallets, "user_wallets_user_id_fkey")

    alter table(:user_wallets) do
      remove :updated_at
      remove :inserted_at
      remove :total_withdrawn
      remove :total_deposited
      remove :balance
      remove :user_id
    end

    drop constraint(:wallet_transactions, "wallet_transactions_wallet_id_fkey")

    alter table(:wallet_transactions) do
      modify :wallet_id, :uuid
    end

    drop table(:user_wallets)

    drop table(:wallet_transactions)
  end
end
