defmodule Angle.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:wallet_transactions, [:wallet_id])
  end

  def down do
    drop_if_exists index(:wallet_transactions, [:wallet_id])
  end
end
