defmodule Angle.Repo.Migrations.AddAutoCharge do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :auto_charge, :boolean, default: false
    end
  end

  def down do
    alter table(:users) do
      remove :auto_charge
    end
  end
end
