defmodule Angle.Repo.Migrations.AddOrderResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "payment_pending"
      add :amount, :decimal, null: false
      add :payment_reference, :text
      add :paid_at, :utc_datetime_usec
      add :dispatched_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:items,
            column: :id,
            name: "orders_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :buyer_id,
          references(:users,
            column: :id,
            name: "orders_buyer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :seller_id,
          references(:users,
            column: :id,
            name: "orders_seller_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:orders, [:item_id, :buyer_id], name: "orders_unique_item_buyer_index")
  end

  def down do
    drop_if_exists unique_index(:orders, [:item_id, :buyer_id],
                     name: "orders_unique_item_buyer_index"
                   )

    drop constraint(:orders, "orders_item_id_fkey")

    drop constraint(:orders, "orders_buyer_id_fkey")

    drop constraint(:orders, "orders_seller_id_fkey")

    drop table(:orders)
  end
end
