defmodule Angle.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # attribute_schema changed from :map (single JSON object) to {:array, :map}
    # (JSON array of objects). Column stays jsonb — only data and default change.
    execute """
    UPDATE categories
    SET attribute_schema = '[]'::jsonb
    WHERE jsonb_typeof(attribute_schema) = 'object'
    """

    execute "ALTER TABLE categories ALTER COLUMN attribute_schema SET DEFAULT '[]'::jsonb"
  end

  def down do
    execute """
    UPDATE categories
    SET attribute_schema = '{}'::jsonb
    WHERE jsonb_typeof(attribute_schema) = 'array'
    """

    execute "ALTER TABLE categories ALTER COLUMN attribute_schema SET DEFAULT '{}'::jsonb"
  end
end
