defmodule Angle.Repo.Migrations.AddPayoutMethods do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:payout_methods, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :bank_name, :text, null: false
      add :bank_code, :text, null: false
      add :account_number, :text, null: false
      add :account_name, :text, null: false
      add :recipient_code, :text, null: false
      add :is_default, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "payout_methods_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:payout_methods, "payout_methods_user_id_fkey")

    drop table(:payout_methods)
  end
end
