defmodule Angle.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_interests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "user_interests_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :category_id,
          references(:categories,
            column: :id,
            name: "user_interests_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :interest_score, :float, null: false, default: 0.0

      add :last_interaction_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :interaction_count, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:user_interests, [:user_id, :interest_score])

    create unique_index(:user_interests, [:user_id, :category_id],
             name: "user_interests_unique_user_category_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_interests, [:user_id, :category_id],
                     name: "user_interests_unique_user_category_index"
                   )

    drop constraint(:user_interests, "user_interests_user_id_fkey")

    drop constraint(:user_interests, "user_interests_category_id_fkey")

    drop_if_exists index(:user_interests, [:user_id, :interest_score])

    drop table(:user_interests)
  end
end
