defmodule Angle.Repo.Migrations.AddFullNameAndPhoneToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :full_name, :text
      add :phone_number, :text
    end

    alter table(:items) do
      modify :attributes, :map, default: %{}
    end

    drop_if_exists constraint(:items, :valid_auction_status)

    create constraint(:items, :valid_auction_status,
             check: """
               (((auction_status IS NULL) OR ((auction_status)::text = ANY (ARRAY[('pending'::character varying)::text, ('scheduled'::character varying)::text, ('active'::character varying)::text, ('paused'::character varying)::text, ('ended'::character varying)::text, ('sold'::character varying)::text, ('cancelled'::character varying)::text]))))
             """
           )
  end

  def down do
    drop_if_exists constraint(:items, :valid_auction_status)

    create constraint(:items, :valid_auction_status,
             check: """
               (((auction_status IS NULL) OR ((auction_status)::text = ANY (ARRAY[('scheduled'::character varying)::text, ('active'::character varying)::text, ('paused'::character varying)::text, ('ended'::character varying)::text, ('sold'::character varying)::text, ('cancelled'::character varying)::text]))))
             """
           )

    alter table(:items) do
      modify :attributes, :map, default: nil
    end

    alter table(:users) do
      remove :phone_number
      remove :full_name
    end
  end
end
