defmodule Angle.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_verifications) do
      add :phone_number, :text
      add :otp_hash, :text
      add :otp_expires_at, :utc_datetime_usec
      add :otp_requested_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:user_verifications) do
      remove :otp_requested_at
      remove :otp_expires_at
      remove :otp_hash
      remove :phone_number
    end
  end
end
