defmodule Angle.Repo.Migrations.AddReviewsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reviews, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :rating, :bigint, null: false
      add :comment, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:orders,
            column: :id,
            name: "reviews_order_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :reviewer_id,
          references(:users,
            column: :id,
            name: "reviews_reviewer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :seller_id,
          references(:users,
            column: :id,
            name: "reviews_seller_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:reviews, [:order_id], name: "reviews_unique_order_review_index")
  end

  def down do
    drop_if_exists unique_index(:reviews, [:order_id], name: "reviews_unique_order_review_index")

    drop constraint(:reviews, "reviews_order_id_fkey")

    drop constraint(:reviews, "reviews_reviewer_id_fkey")

    drop constraint(:reviews, "reviews_seller_id_fkey")

    drop table(:reviews)
  end
end
