defmodule Angle.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :owner_type, :text, null: false
      add :owner_id, :uuid, null: false
      add :storage_key, :text, null: false
      add :variants, :map, null: false, default: %{}
      add :position, :bigint, null: false, default: 0
      add :file_size, :bigint, null: false
      add :mime_type, :text, null: false
      add :width, :bigint, null: false
      add :height, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:images, [:owner_type, :owner_id, :position],
             name: "images_unique_position_index"
           )
  end

  def down do
    drop_if_exists unique_index(:images, [:owner_type, :owner_id, :position],
                     name: "images_unique_position_index"
                   )

    drop table(:images)
  end
end
