defmodule Angle.Repo.Migrations.AddPaymentMethods do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:payment_methods, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :card_type, :text, null: false
      add :last_four, :text, null: false
      add :exp_month, :text, null: false
      add :exp_year, :text, null: false
      add :authorization_code, :text, null: false
      add :bank, :text
      add :is_default, :boolean, default: false
      add :paystack_reference, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "payment_methods_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:payment_methods, [:paystack_reference],
             name: "payment_methods_unique_reference_index"
           )
  end

  def down do
    drop_if_exists unique_index(:payment_methods, [:paystack_reference],
                     name: "payment_methods_unique_reference_index"
                   )

    drop constraint(:payment_methods, "payment_methods_user_id_fkey")

    drop table(:payment_methods)
  end
end
