defmodule Angle.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:recommended_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :recommendation_score, :float, null: false
      add :recommendation_reason, :text
      add :rank, :bigint, null: false

      add :generated_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "recommended_items_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :item_id,
          references(:items,
            column: :id,
            name: "recommended_items_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:recommended_items, [:generated_at])

    create index(:recommended_items, [:user_id, :rank])

    create unique_index(:recommended_items, [:user_id, :item_id],
             name: "recommended_items_unique_user_item_index"
           )

    create unique_index(:item_similarities, [:source_item_id, :similar_item_id],
             name: "item_similarities_unique_source_similar_index"
           )
  end

  def down do
    drop_if_exists unique_index(:item_similarities, [:source_item_id, :similar_item_id],
                     name: "item_similarities_unique_source_similar_index"
                   )

    drop_if_exists unique_index(:recommended_items, [:user_id, :item_id],
                     name: "recommended_items_unique_user_item_index"
                   )

    drop constraint(:recommended_items, "recommended_items_user_id_fkey")

    drop constraint(:recommended_items, "recommended_items_item_id_fkey")

    drop_if_exists index(:recommended_items, [:user_id, :rank])

    drop_if_exists index(:recommended_items, [:generated_at])

    drop table(:recommended_items)
  end
end
