defmodule Angle.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Convert existing empty maps to empty arrays before altering the column type
    execute "UPDATE categories SET attribute_schema = '[]'::jsonb WHERE attribute_schema = '{}'::jsonb"

    alter table(:categories) do
      modify :attribute_schema, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:categories) do
      modify :attribute_schema, :map, default: %{}
    end
  end
end
