defmodule Angle.Repo.Migrations.ConsolidateCoreBidding do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:wallet_transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :decimal, null: false, precision: 15, scale: 2
      add :transaction_type, :text, null: false
      add :balance_before, :decimal, null: false, precision: 15, scale: 2
      add :balance_after, :decimal, null: false, precision: 15, scale: 2
      add :reference, :text, null: false
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :wallet_id, :uuid, null: false
    end

    create index(:wallet_transactions, [:wallet_id])

    create table(:user_wallets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:wallet_transactions) do
      modify :wallet_id,
             references(:user_wallets,
               column: :id,
               name: "wallet_transactions_wallet_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:user_wallets) do
      add :balance, :decimal, null: false, default: "0", precision: 15, scale: 2
      add :total_deposited, :decimal, null: false, default: "0", precision: 15, scale: 2
      add :total_withdrawn, :decimal, null: false, default: "0", precision: 15, scale: 2
      add :paystack_subaccount_code, :text
      add :last_synced_at, :utc_datetime
      add :sync_status, :text, null: false, default: "pending"
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_wallets_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:user_wallets, [:paystack_subaccount_code],
             name: "user_wallets_unique_paystack_subaccount_index"
           )

    create unique_index(:user_wallets, [:user_id], name: "user_wallets_unique_user_wallet_index")

    create table(:user_verifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :phone_verified, :boolean, null: false, default: false
      add :phone_verified_at, :utc_datetime_usec
      add :phone_number, :text
      add :otp_hash, :text
      add :otp_expires_at, :utc_datetime_usec
      add :otp_requested_at, :utc_datetime_usec
      add :otp_attempts, :bigint, null: false, default: 0
      add :id_verified, :boolean, null: false, default: false
      add :id_document_url, :text
      add :id_verified_at, :utc_datetime_usec
      add :id_verification_status, :text, null: false, default: "not_submitted"
      add :id_rejection_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_verifications_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:user_verifications, [:user_id],
             name: "user_verifications_unique_user_verification_index"
           )

    alter table(:items) do
      add :extension_count, :bigint, default: 0
      add :original_end_time, :utc_datetime_usec
    end
  end

  def down do
    alter table(:items) do
      remove :original_end_time
      remove :extension_count
    end

    drop_if_exists unique_index(:user_verifications, [:user_id],
                     name: "user_verifications_unique_user_verification_index"
                   )

    drop constraint(:user_verifications, "user_verifications_user_id_fkey")

    drop table(:user_verifications)

    drop_if_exists unique_index(:user_wallets, [:user_id],
                     name: "user_wallets_unique_user_wallet_index"
                   )

    drop_if_exists unique_index(:user_wallets, [:paystack_subaccount_code],
                     name: "user_wallets_unique_paystack_subaccount_index"
                   )

    drop constraint(:user_wallets, "user_wallets_user_id_fkey")

    alter table(:user_wallets) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :metadata
      remove :sync_status
      remove :last_synced_at
      remove :paystack_subaccount_code
      remove :total_withdrawn
      remove :total_deposited
      remove :balance
    end

    drop constraint(:wallet_transactions, "wallet_transactions_wallet_id_fkey")

    alter table(:wallet_transactions) do
      modify :wallet_id, :uuid
    end

    drop table(:user_wallets)

    drop_if_exists index(:wallet_transactions, [:wallet_id])

    drop table(:wallet_transactions)
  end
end
