defmodule Angle.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:user_wallets, [:paystack_subaccount_code],
             name: "user_wallets_unique_paystack_subaccount_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_wallets, [:paystack_subaccount_code],
                     name: "user_wallets_unique_paystack_subaccount_index"
                   )
  end
end
