defmodule Angle.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      add :extension_count, :bigint, default: 0
      add :original_end_time, :utc_datetime_usec
    end
  end

  def down do
    alter table(:items) do
      remove :original_end_time
      remove :extension_count
    end
  end
end
